# Generated by Django 3.2.2 on 2021-05-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=100, verbose_name='Identificador'),
        ),
    ]
